name: CI Tests

on:
#  push:
#    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_ubuntu2004:
    runs-on: ubuntu-latest
    container: solidity-buildpack-deps:ubuntu2004-2
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -G Ninja
          ninja
      - name: Store Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build_ubuntu2004
          path: build/
  test_ubuntu2004:
    needs: build_ubuntu2004
    runs-on: ubuntu-latest
    container: solidity-buildpack-deps:ubuntu2004-2
    steps:
      - name: Attach build
        uses: actions/download-artifact@v1
        with:
          name: build_ubuntu2004
      - name: soltest
        run: |
          build/test/soltest --show-progress --logger=JUNIT,error,test_results/soltest.xml
